jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines$'

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userportal
    password: root@2022
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect